### ISSUE TITLE
Create Playlist/Search - must handle no search results back

### ISSUE THREAD

**Issue by thurston-ssa** [ajvernet/PlaylistGen#13]
Reproduce:
- Go to Create Playlist
- Enter "atavists" in the google search box
- Click Search
- Loading spins and never stops spinning

JSON Response was {"status":"SUCCESS","msg":"You got search results","obj":[]}

@DmartGit 

*_Priority:  High *_

**Comment by DMartMD** [comment]
@thurston-ssa 
Verify

**Comment by thurston-ssa** [comment]
verified/closing
