### ISSUE TITLE
Create Playlist View - Sort Headers shouldn't display by default

### ISSUE THREAD

**Issue by thurston-ssa** [ajvernet/PlaylistGen#9]
When clicking on the create playlist menu item - the view that is displayed shows the sort headers (show name, episode title, length) even though there has been no search yet (and therefore no search results yet); those sort headers should only display when there are actually search results to sort (should just be a ng-show) to take care of it

@DmartGit

**Comment by DMartMD** [comment]
@thurston-ssa 
Verify

**Comment by thurston-ssa** [comment]
Verified/closing
